@startjson
{
    "states": {
        "__top__": {
            "pos": [-100000000,-100000000],
            "size": [200000000,200000000],
            "title": "__top__",
            "text": [],
            "connectors": [],
            "parent": null,
            "children": ["state_0","istate_0"],
            "type": "top"
        },
        "state_0": {
            "pos": [34,24],
            "size": [98,42],
            "title": "s_ltc2471",
            "text": ["SIG_SYS_TICK_1ms/ ltc2471_1ms_callack()"],
            "connectors": ["conn_3"],
            "parent": "__top__",
            "children": ["state_1","state_2","istate_1"],
            "type": "normal"
        },
        "state_1": {
            "pos": [
                41,
                43
            ],
            "size": [
                18,
                19
            ],
            "title": "s_idle",
            "text": [
                "init/ ltc2471_restart_timer()"
            ],
            "connectors": [
                "conn_0",
                "conn_5",
                "conn_7",
                "conn_9",
                "conn_11"
            ],
            "parent": "state_0",
            "children": [],
            "type": "normal"
        },
        "state_2": {
            "pos": [
                108,
                43
            ],
            "size": [
                20,
                19
            ],
            "title": "s_reading",
            "text": [
                "entry/ ltc2471_start_read()",
                "init/ ltc2471_restart_timer()"
            ],
            "connectors": [
                "conn_1",
                "conn_6",
                "conn_8",
                "conn_10"
            ],
            "parent": "state_0",
            "children": [],
            "type": "normal"
        },
        "istate_0": {
            "pos": [
                77,
                20
            ],
            "size": [
                2,
                2
            ],
            "title": "istate_0",
            "text": [
                "entry/",
                "exit/"
            ],
            "connectors": [
                "conn_2"
            ],
            "parent": "__top__",
            "children": [],
            "type": "initial"
        },
        "istate_1": {
            "pos": [
                48,
                39
            ],
            "size": [
                2,
                2
            ],
            "title": "istate_1",
            "text": [
                "entry/",
                "exit/"
            ],
            "connectors": [
                "conn_4"
            ],
            "parent": "state_0",
            "children": [],
            "type": "initial"
        }
    },
    "connectors": {
        "conn_0": {
            "parent": "state_1",
            "offset": 5,
            "side": "right",
            "dir": "out",
            "transition": "trans_0"
        },
        "conn_1": {
            "parent": "state_2",
            "offset": 5,
            "side": "left",
            "dir": "in",
            "transition": "trans_0"
        },
        "conn_2": {
            "parent": "istate_0",
            "offset": 0,
            "side": "all",
            "dir": "out",
            "transition": "trans_1"
        },
        "conn_3": {
            "parent": "state_0",
            "offset": 43,
            "side": "top",
            "dir": "in",
            "transition": "trans_1"
        },
        "conn_4": {
            "parent": "istate_1",
            "offset": 0,
            "side": "all",
            "dir": "out",
            "transition": "trans_2"
        },
        "conn_5": {
            "parent": "state_1",
            "offset": 7,
            "side": "top",
            "dir": "in",
            "transition": "trans_2"
        },
        "conn_6": {
            "parent": "state_2",
            "offset": 8,
            "side": "left",
            "dir": "out",
            "transition": "trans_3"
        },
        "conn_7": {
            "parent": "state_1",
            "offset": 8,
            "side": "right",
            "dir": "in",
            "transition": "trans_3"
        },
        "conn_8": {
            "parent": "state_2",
            "offset": 11,
            "side": "left",
            "dir": "out",
            "transition": "trans_4"
        },
        "conn_9": {
            "parent": "state_1",
            "offset": 11,
            "side": "right",
            "dir": "in",
            "transition": "trans_4"
        },
        "conn_10": {
            "parent": "state_2",
            "offset": 14,
            "side": "left",
            "dir": "out",
            "transition": "trans_5"
        },
        "conn_11": {
            "parent": "state_1",
            "offset": 14,
            "side": "right",
            "dir": "in",
            "transition": "trans_5"
        }
    },
    "transitions": {
        "trans_0": {
            "start": "conn_0",
            "end": "conn_1",
            "vertices": [
                [
                    59,
                    48
                ],
                [
                    78,
                    48
                ],
                [
                    78,
                    48
                ],
                [
                    108,
                    48
                ]
            ],
            "label": "[ltc2471_timeout(LTC2471_READ_TIMEOUT)]",
            "label_offset": [
                5,
                -0.3999999999999986
            ],
            "label_anchor": 0,
            "label_pos": [
                64,
                47.6
            ]
        },
        "trans_1": {
            "start": "conn_2",
            "end": "conn_3",
            "vertices": [
                [
                    77,
                    20
                ],
                [
                    77,
                    20
                ],
                [
                    77,
                    24
                ]
            ],
            "label": "",
            "label_offset": [
                0.5,
                1.6000000000000014
            ],
            "label_anchor": 1,
            "label_pos": [
                77.5,
                21.6
            ]
        },
        "trans_2": {
            "start": "conn_4",
            "end": "conn_5",
            "vertices": [
                [
                    48,
                    39
                ],
                [
                    48,
                    39
                ],
                [
                    48,
                    43
                ]
            ],
            "label": "",
            "label_offset": [
                0.5,
                -0.3999999999999986
            ],
            "label_anchor": 1,
            "label_pos": [
                48.5,
                38.6
            ]
        },
        "trans_3": {
            "start": "conn_6",
            "end": "conn_7",
            "vertices": [
                [
                    108,
                    51
                ],
                [
                    78,
                    51
                ],
                [
                    78,
                    51
                ],
                [
                    59,
                    51
                ]
            ],
            "label": "SIG_I2C_RESULT_SUCCESS/ ltc2471_update_sample()",
            "label_offset": [
                -14,
                -0.3999999999999986
            ],
            "label_anchor": 2,
            "label_pos": [
                64,
                50.6
            ]
        },
        "trans_4": {
            "start": "conn_8",
            "end": "conn_9",
            "vertices": [
                [
                    108,
                    54
                ],
                [
                    80,
                    54
                ],
                [
                    80,
                    54
                ],
                [
                    59,
                    54
                ]
            ],
            "label": "SIG_I2C_RESULT_ADDR_NACK/ ltc2471_invalidate_sample()",
            "label_offset": [
                -16,
                -0.3999999999999986
            ],
            "label_anchor": 2,
            "label_pos": [
                64,
                53.6
            ]
        },
        "trans_5": {
            "start": "conn_10",
            "end": "conn_11",
            "vertices": [
                [
                    108,
                    57
                ],
                [
                    80,
                    57
                ],
                [
                    80,
                    57
                ],
                [
                    59,
                    57
                ]
            ],
            "label": "[ltc2471_timeout(LTC2471_READ_TIMEOUT)]/ ltc2471_invalidate_sample()",
            "label_offset": [
                -16,
                -0.3999999999999986
            ],
            "label_anchor": 2,
            "label_pos": [
                64,
                56.6
            ]
        }
    },
    "notes": {
        "ltc2471_timeout": "",
        "SIG_I2C_RESULT_SUCCESS": "",
        "ltc2471_update_sample()": "",
        "invalidate_sample()": "",
        "LTC2471_READ_TIMEOUT": "",
        "ltc2471_1ms_callack()": "",
        "ltc2471_start_read()": "",
        "SIG_SYS_TICK_1ms": ""
    },
    "view": {
        "translate": [
            -258,
            -151.5
        ],
        "scale": 11.5
    }
}
@endjson