@startuml
title Smart Home Automation System Architecture

package "Sensors and Actuators" {
  [temp_sensor]
  [humidity_sensor]
  [motion_sensor] 
  [light_sensor]
  [thermostat] 
  [smart_plug] 
  [smart_bulb] 
}

package "Central Hub" as center_hub {
  [control_center] 
  center_int2 -[data_logger] 
  center_int - [comm_module] 
}

center_int3 - center_hub 
temp_sensor --( center_int
humidity_sensor --> control_center
motion_sensor -u-( center_int3
motion_sensor --> control_center
light_sensor --> control_center
thermostat --> control_center
smart_plug --> control_center
smart_bulb --> control_center

control_center --> data_logger
control_center --> comm_module

' Data Logger --> Local Storage

' Communication Module --> WiFi Module
@enduml