@startuml sm_gen_swad
scale 800 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam cloud {
  backgroundColor Olive
  borderColor orange
}

title Architecture Diagram of the CHSM package

left to right direction

package "sm_gen" as sm_gen{

package "cgen" as cgen{
    package "sm" as sm{
        class StateMachine{
           -_get_user_symbols 
           +build_user_declarations
           +get_transition_funcs
           +process_transitions
           +delete_non_leaf_states
           +add_parent_signals
           +add_parent_signals_to_state
           +str_to_signal
           +add_signal_to_state
           +get_states
           +resolve_parent_titles
           +resolve_transition
           +add_transitions_to_states
           +make_call
           +guard_to_ast
           +build_case_from_signal
           +build_func_from_state
           +build_ast
           +get_entry_path
           +is_in
           +get_LCA
           +get_exit_path
           +get_transition_path
           +get_init_path
           +path_to_funcs
        }
    }
    package "ast" as ast{
        class "Ast"{}
        class "Node"{}
        class "Comment"{}
        class "Include"{}
        class "ifndef"{}
        class "Define"{}
        class "Endif"{}
        class "Block"{}
        class "If"{}
        class "switch"{}
        class "Break"{}
        class "Decl"{}
        class "Enum"{}
        class "Argument"{}
        class "Blank"{}
        class "Case"{}
        class "FunctionDeclaration"{}
        class "Func"{}
        class "Call"{}
        class "Expr"{}
        class "Return"{
            -void
        }
    }
}
package "pygen" as pygen{}
package "jsgen" as jsgen{}
package "javagen" as javagen{}
}


@enduml