name: Build and Deploy Documentation

on:
  push:
    branches:
      - feature/multi_lang_sm_gen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Sphinx m2r sphinxcontrib-plantuml sphinx-rtd-dark-mode sphinxcontrib-datatemplates sphinxcontrib-drawio

    - name: Install Draw.io
      run: |
        sudo apt-get update
        sudo apt install snapd
        sudo snap install drawio
    
    - name: Build documentation
      run: |
        cd doc/doc_gen
        make html
        ls -lah
        tree

    - name: Init new repo in dist folder and commit generated files
      run: |
          pwd
          ls -lah
          cd ./doc/doc_gen/build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

    # - name: Force push to destination branch
    #   uses: ad-m/github-push-action@v0.5.0
    #   with:
    #       branch: gh-pages
    #       force: true
    #       directory: ./doc/doc_gen/build/html
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages  # This is the branch the action should deploy to.
        folder: ./doc/doc_gen/build/html  # This is the folder the action should deploy.
