name: Build and Deploy Documentation

on:
  push:
    branches:
      - feature/multi_lang_sm_gen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Sphinx m2r sphinxcontrib-plantuml sphinx-rtd-dark-mode sphinxcontrib-datatemplates sphinxcontrib-drawio

    - name: Install Draw.io
      run: |
        sudo apt-get update
        sudo apt install snapd
        sudo snap install drawio
    
    - name: Build documentation
      run: |
        cd doc/doc_gen
        make html
        ls -lah
        tree

  pages:
    runs-on: ubuntu-20.04
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    permissions:
        pages: write
        id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish_dir: doc/doc_gen/build/html/

