name: Build and Deploy Documentation

on:
  push:
    branches:
      - feature/multi_lang_sm_gen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Sphinx m2r sphinxcontrib-plantuml sphinx-rtd-dark-mode sphinxcontrib-datatemplates sphinxcontrib-drawio

    - name: Install Draw.io
      uses: severgroup-tt/actions-drawio-cli@v1.0.0
    
    - name: Build documentation
      run: |
        cd doc/doc_gen
        make html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages  # This is the branch the action should deploy to.
        folder: doc/doc_gen/build/html  # This is the folder the action should deploy.
